package com.ferbotz.aurapix.core.data.local

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import com.ferbotz.aurapix.creation.data.local.CreationDao
import com.ferbotz.aurapix.creation.data.local.CreationEntity

@Database(entities = [CreationEntity::class], version = 2)
@ConstructedBy(AppDatabaseConstructor::class)
abstract class AppDatabase : RoomDatabase() {
    abstract fun creationDao(): CreationDao
}

/**
 * The `actual` implementation is generated by the Room compiler (KSP) for each platform.
 * The IDE can't see it, so the "no actual for expect" warnings are suppressed.
 */
@Suppress("KotlinNoActualForExpect", "NO_ACTUAL_FOR_EXPECT", "EXPECT_ACTUAL_CLASSIFIERS_ARE_IN_BETA_WARNING")
expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase> {
    override fun initialize(): AppDatabase
}
